/*

Antonina (Toni) York
OSU CS 362 Winter 2017
Random Testing Quiz
testme.c

notes: see randomtesting.c
compile: gcc -g -Wall testme.c -o testme

*/

#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<time.h>

// define the set of valid characters for random character generation
const int CHARSET_SIZE = 13;
const char CHARSET[] = 
			{' ', 'a', 'e', 'r', 's', 't', 'x', '(', ')', '[', ']', '{', '}'};
			
// define the length of the generated string
#define STR_LENGTH 5

// Returns a randomly generated character from the set of CHARSET_SIZE
// characters in the CHARSET.
char inputChar()
{	
    return CHARSET[rand() % CHARSET_SIZE];
}

// Returns a randomly generated STR_LENGTH-character, null-terminated string
// whose characters come from the CHARSET, generated by calling inputChar().
// In the case of generating 5-letter words using the above 13-character set,
// this should return the string "reset" on the order of 1 out of every
// 13^5 = 371,293 calls.
char *inputString()
{
    // malloc space for the string
	char* str = malloc((STR_LENGTH + 1) * sizeof(char));
	
	// randomly generate the rest of the string by calling inputChar()
	int i;
	for (i = 0; i < STR_LENGTH; i++)
		str[i] = inputChar();
	
	// set the null-terminator
	str[STR_LENGTH] = '\0';
	
    // return the generated string
	return str;
}

void testme()
{
  int tcCount = 0;
  char *s;
  char c;
  int state = 0;
  while (1)
  {
    tcCount++;
    c = inputChar();
    s = inputString();
    printf("Iteration %d: c = %c, s = %s, state = %d\n", tcCount, c, s, state);

    if (c == '[' && state == 0) state = 1;
    if (c == '(' && state == 1) state = 2;
    if (c == '{' && state == 2) state = 3;
    if (c == ' '&& state == 3) state = 4;
    if (c == 'a' && state == 4) state = 5;
    if (c == 'x' && state == 5) state = 6;
    if (c == '}' && state == 6) state = 7;
    if (c == ')' && state == 7) state = 8;
    if (c == ']' && state == 8) state = 9;
    if (s[0] == 'r' && s[1] == 'e'
       && s[2] == 's' && s[3] == 'e'
       && s[4] == 't' && s[5] == '\0'
       && state == 9)
    {
      // free memory malloced for the string by the call to inputString()
	  free(s);
	  
	  printf("error\n");
      exit(200);
    }
	
	// free memory malloced for the string by the call to inputString()
	free(s);
  }
}

int main(int argc, char *argv[])
{
    srand(time(NULL));
    testme();
    return 0;
}
