
/*================================================================================================
 File			: randomstring.c 
 Author			: Matthew Hillman (CS 362 Winter 2017)
 Date			: February 1, 2017
 Description	:  Write up of the development of a random tester (testme.c) including an 
 explanation of how the code works and outputs the error message.
  
==================================================================================================
*/

In the file testme.c, the function testme() receives a char and a string each time a while loop
executes.  The char input is tested in testme() against a specific char, e.g. [ and if it matches
the varible, state, is increased by one.  A new test then becomes active, looking for another specific
char.  For this section of code, the variable state should start at 0 and then have values 1, 2...9.
With random char input that includes the specified chars, the state variable should rise, very quickly
to 9 and then remain at 9 until the loop exits.  We can check this since since a printf outputs the 
value of state for each pass through the loop.  Specifically, the inputChar() was coded to randomly 
return one of the 95 characters between space (ASCII 32) and tilde~ (ASCII 126), this includes all of
the chars required for state to reach 9.  The program was run and output to a file, then the file inspected,
it was found that state increased from 1 to 9 correctly and reached 9 after 912 lines, very close to 95X9=855
which is what we would expect if a large amount of tests were run and then averaged.  The test file 
inspection also showed that state remained 9 until the loop exited.  The second part of the program
received a string of length six and tested the string against the string reset\0.  When the test is met,
the loop is supposed to exit and print 'error'.  Iniitally, a random string was generated by calling 
inputChar(), thus each of the five chars in the string could be one of 95 chars.  This ran too slow and
never finished.  It is estimated that this would require, on average, about 1E10 passes through the loop
to execute, and on FLIP that would take several days.  So, the inputString was modified to return a 
string having 5 chars and a null at the end, where each of the 5 chars was one of the 26 lower case 
letters.  With this process, we were able to test several things, including, that the loop does not exit
with something other than reset\0, that the loop exits, on average after about the right number of passes, 
and that the loop exits with reset.  These checks were confirmed during testing.  The loop exited after
12.966,731 passes with reset\0 which is close to our estimate of 26^5 = 11,881,376.  Thus, roughly 
12,000,000 other strings failed to cause the function to exit. Pretty good test!  
In short, our testing found no bugs in the testme() program.


