/* CS362 - Random Testing Quiz 2 - William Miller
 *
 * My implementation of inputChar() and inputString() to reach the error message generated by
 * the condition where the state variable == 9 and when the s character string == "reset\0"
 * works as follows: 
 *
 * First, the inputChar() fucntion generates a random character between 32 and and 127
 * (the printable ASCII characters) and stores that in the c variable, which is tested for
 * a match with the 9 characters which trigger the state variable to increment.
 *
 * The inputString() function works in a similar way, but if only random characters are selected
 * to be assigned to the dynamically allocated string which is pointed to by the c variable, 
 * it takes far too long to find a match (there are 96^5 or 8.2e9 possible combinations
 * of printable characters for a 5 character string). My solution was to simply
 * make a 1 in 2 chance (rand() % 2) that the string is generated from random characters or
 * from a preset array of characters which constitute the word "reset". In this way, the test
 * conducts a fair amount of tests with random strings, but also includes the input more
 * meaningful to the domain of the function. Ideally, if we had the time or resources, a
 * completely exhasutive test could be conducted with only random inputs.
