/*********************************************************************
testme.c is a random tester that uses the inputChar() function to 
generate pseudo-random chars in the range [0, 127], all of the
available chars in the ascii table. The inputString() funciton is used
to generate a string of length 6 (5 chars and a terminating character).
The characters to populate the string are permutations of the chars 'r',
'e', 's', and 't'. The char array is populated with pseudo-randomly
generated permutations of those available chars.

The overall test first uses inputChar() to generate chars until a
specified char is returned. There are 9 pre-specified chars that must
be generated by the inputChar() function. Once all 9 of the pre-defined
chars have been generated, the inputString() function is used to
generate strings until the pre-defined permutation of the designated
chars are returned.

An pseudocode example of the test is as follows:

pre-defined char: '['
run inputChar() continuously until '[' is generated

pre-defined char: 'a'
run inputChar() continuously until 'a' is generated

...

pre-defined char: 'x'
run inputChar() continuously until 'x' is generated

pre-defined string 'reset'
run inputString() continuously until 'reset' is generated
*********************************************************************/